### ISSUE TITLE
Warnings and Errors should log sequence points

### ISSUE THREAD

**Issue by Keboo** [Keboo/AutoDI#13]
Currently the weaver just logs warnings to the output window. This is ok, but it would be better to log with the sequence point so the user can simply click the warning to navigate.

The LogError and LogWarning delegate properties have an additional overload that also logs the sequence point. AutoDI should be calling these overloads and including the sequence points so it is obvious where the problems are located.

At a minimum, all the error/warning messages should indicate at least the file, and enough information so the offending code can be easily located.

**Comment by gethari** [comment]
@Keboo can i work on this ?

**Comment by Keboo** [comment]
@gethari yes thank you. I haven't looked too closely at the details so if you have questions let me know.

**Comment by gethari** [comment]
@Keboo yup i have some questions.

````
At a minimum, all the error/warning messages should indicate at least the file, and enough 

information so the offending code can be easily located.
````

This means everywhere where the exceptions are thrown inside the catch block am i right ? I have'nt explored the source fully. Is there a separate logger instance or something that needs to be added or something as such ?

**Comment by gethari** [comment]
@Keboo i will check when i get some time

**Comment by gethari** [comment]
@Keboo I have done the changes. But in some places like `SetupMethod` in Build, there are some warnings thrown without an Exception. What should i throw there ? 

My current implementation looks like this. I wrote a StackTracer class to get the information needed like filename,classname, column, line etc..

````
 var additionalInformation = StackTracer.GetStackTrace(e);
Logger.Error($"some message",additionalInformation);
````

Let me know how can i proceeed

**Comment by Keboo** [comment]
@gethari thanks, I will take a look at the PR later and let you know.

**Comment by gethari** [comment]
👀 @Keboo Waiting on your review 👂

**Comment by AlexanderGipp** [comment]
Why didnt you guys continue the work on this? 

If this is not too hard could i take a look at this issue?

**Comment by Keboo** [comment]
O shoot, I think I simply lost track of this one and I apologize (so many GitHub issues, so little time...).
First, yes @AlexanderGipp if you want to take a crack at getting this done feel free (you may also want to take a look at the above PR; it is good but not complete). A few things to keep in mind.

Just in terms of definitions, SequencePoint the point where something occurs in the code. It is made up of a file path, a line number, and a column number. You can see these in things like the Errors window in Visual Studio. This is what enables clicking on an item in that window and having it navigate to the issue.

Next, these sequence points should be tied to the code in the project where AutoDI is applied (remember, this project runs on post-compilation on another project to add in dependency injection). It is not expected to be the sequence point within AutoDI code. 

The key thing to hunt down are the calls to `ILogger.Warning` and `ILogger.Error`. In some cases, there may not be reasonable sequence points that can be specified, however the intent is to try and track the ones where it is possible and provide them.

**Comment by AlexanderGipp** [comment]
Also @Keboo is this going in the right direction / could you check if this makes sense?
https://github.com/AlexanderGipp/AutoDI/commit/e3cbb64271cf947000f8a17ad250f78379b6fcae

**Comment by Keboo** [comment]
@AlexanderGipp I don't think a StackTracer should be needed. That would only help with tracking the sequence point within this library. Really the sequence points being logged are there to help consumers of this library and get directed to the location in their code not the code in this library.

As for your progress, it looks good as what I would expect.

**Comment by AlexanderGipp** [comment]
This should probably be closed @Keboo

**Comment by Keboo** [comment]
@AlexanderGipp thank you!
