### ISSUE TITLE
Issue with portable PDB files in 4.0.2 preview

### ISSUE THREAD

**Issue by KennethWhite** [Keboo/AutoDI#157]
Details: After compiling library can no longer place/hit breakpoints in library.

- Compiled with .NET Core SDK

 AutoDI Settings:
- Behavior(s): None
- AutoInit: True
- GenerateRegistrations: True
- DebugLogLevel: Default
- DebugExceptions: False
- Included Assemblies: <none>
- Maps: <none>
- Type Lifetimes: <none>

**Comment by Keboo** [comment]
For reference: https://github.com/jbevain/cecil/issues/282
