### ISSUE TITLE
Rename InitMode.None to InitMode.Manual

### ISSUE THREAD

**Issue by Keboo** [Keboo/AutoDI#169]

**Comment by petrechitashvili** [comment]
There's a typo in the description of this issue:

### InitMode.None to InitMode.Man**~~a~~**ual -> InitMode.None to InitMode.Manual

Cheers!
And a happy new year! 🙂

**Comment by AlexanderGipp** [comment]
This should probably be closed @Keboo

**Comment by Keboo** [comment]
@AlexanderGipp thank you!
