### ISSUE TITLE
Cleanup ThirdParty folder

### ISSUE THREAD

**Issue by Keboo** [Keboo/AutoDI#64]
Right now there is a ThirdParty directory at the root of the repository. This should be merged into the Examples\ThirdParty directory and the appropriate project references updated.

**Comment by hannahkriegler** [comment]
I'd like to work on this

**Comment by Keboo** [comment]
@hannahkriegler go for it, if you have any questions let me know.

**Comment by Keboo** [comment]
@hannahkriegler are you still working on this?

**Comment by dutts** [comment]
Happy to take a look at this if you still need help?

**Comment by Keboo** [comment]
@dutts yes please. If you have any questions or issues please let me know.

**Comment by Keboo** [comment]
@dutts just following up. Are you still interested in working on this?

**Comment by dutts** [comment]
Hyy, sorry @Keboo, I couldn't build under VS for Mac and hadn't got around to digging out my Windows dev machine.

**Comment by Keboo** [comment]
@dutts no problem. I had some extra time, so just cleaning up the remaining issues for the 3.1.0 release.
