### ISSUE TITLE
AutoFac example

### ISSUE THREAD

**Issue by Keboo** [Keboo/AutoDI#65]
It would be nice to have a simple example using AutoFac, similar to the StructureMap and MS thirdParty examples.

A simple dotnet core console application similar to the projects [here](https://github.com/Keboo/AutoDI/tree/master/Examples/ThirdParty/Microsoft.Console.Core) and [here](https://github.com/Keboo/AutoDI/tree/master/Examples/ThirdParty/StructureMap.Console.Core). The AutoFac example should also be in the /Examples/ThirdParty directory (like those two examples). 

Rather than creating a separate project (like what I did with StructureMap.AutoDI), I think it would be cleaner to just create an AutoFac equivelent of [ApplicationBuilderMixins](https://github.com/Keboo/AutoDI/blob/master/ThirdParty/StructureMap/StructureMap.AutoDI/ApplicationBuilderMixins.cs) directly inside the example dotnet core console application rather than in a separate project. I am assuming we can simply add a reference to the `Autofac.Extensions.DependencyInjection` package and use the classes in there to get similar results. 

Also note that examples are being moved to the wiki so this is where the documentation should go.

**Comment by lonestar1997** [comment]
Hello, can you explain what you want, i think i can help you

**Comment by Keboo** [comment]
Hi @lonestar1997 

Yes. I am expecting a simple dotnet core console application similar to the projects [here](https://github.com/Keboo/AutoDI/tree/master/Examples/ThirdParty/Microsoft.Console.Core) and [here](https://github.com/Keboo/AutoDI/tree/master/Examples/ThirdParty/StructureMap.Console.Core). The AutoFac example should also be in the /Examples/ThirdParty directory (like those two examples). 

Rather than creating a separate project (like what I did with StructureMap.AutoDI), I think it would be cleaner to just create an AutoFac equivelent of [ApplicationBuilderMixins] (https://github.com/Keboo/AutoDI/blob/master/ThirdParty/StructureMap/StructureMap.AutoDI/ApplicationBuilderMixins.cs) directly inside the example dotnet core console application rather than in a separate project. I am assuming we can simply add a reference to the `Autofac.Extensions.DependencyInjection` package and use the classes in there to get similar results. 

If you run into issues or have questions let me know.

**Comment by lonestar1997** [comment]
I have issues with restore nuget packages

**Comment by Keboo** [comment]
@lonestar1997 which projects and which nugets?
If they are projects in the Examples solution you can simply unload them. There is an outstanding issue #67 to update these projects from the private nuget feed to the released 3.0.0 nuget.

**Comment by lonestar1997** [comment]
Ok, I understand

**Comment by Keboo** [comment]
Just a note for when I get back around to doing this:

- Added NuGet Autofac.Extensions.DependencyInjection
- Add the following extension class
```C#
public static class AutoFacExtensions
{
    public static IApplicationBuilder UseAutofac(this IApplicationBuilder applicationBuilder)
    {
        return applicationBuilder.ConfigureServices(services => services.AddAutofac(builder =>
        {
            //Any manual AutoFac registrations
        }));
    }
}
```
- Change the `SetupMethod` to look like this:
```C#
[SetupMethod]
public static void Initialize(IApplicationBuilder builder)
{
    builder.UseAutofac();
}
```

**Comment by Keboo** [comment]
This is completed with an example here: https://github.com/Keboo/AutoDI.Examples/tree/master/ThirdParty/Autofac/Autofac.Console.Core
