### ISSUE TITLE
Update all examples to 3.0.0 release

### ISSUE THREAD

**Issue by Keboo** [Keboo/AutoDI#67]
All of the projects in the [Examples](https://github.com/Keboo/AutoDI/blob/master/Examples/) should be updated to the latest 3.0.0 NuGet release of AutoDI.
This should come from release on nuget.org.

**Comment by adamskt** [comment]
Do you want the examples to pull the latest nuget from the public feed, or from local source?

**Comment by Keboo** [comment]
@adamskt just the latest from the public feed.
