### ISSUE TITLE
GlobalDI.GetService needs more overloads

### ISSUE THREAD

**Issue by Keboo** [Keboo/AutoDI#71]
The [GlobalDI class](https://github.com/Keboo/AutoDI/blob/master/AutoDI/GlobalDI.cs) currently has a single `T GetService<T>(object[])` method. This method simply wrapps calls into `IServiceProvider.GetService`.

The following overloads should be added:
- [ ] `T GetService<T>()` - this should simply call the original method passing an empty array for the parameters.
- [ ] `object GetService(Type serviceType, object[] parameters)` - Same as the original method but should call the non-generic version of the `IServiceProvider.GetService` method.
- [ ] `object GetService(Type serviceType)` - Should call the method above passing an empty array for the parameters.

**Comment by hbbq** [comment]
@Keboo,

The new overloads conflicts with the following code in [AutoDI.Fody/ModuleWeaver.Imports.cs](https://github.com/Keboo/AutoDI/blob/master/AutoDI.Fody/ModuleWeaver.Imports.cs), line 46:

```csharp
GlobalDI_GetService = moduleDefinition.ImportReference(UpdateMethod(globalDiType.GetMethods()
    .Single(m => m.Name == nameof(GlobalDI.GetService))));
```

As there are now more than one method with the same name `.Single` throws an error.
It could be solved by changing the code to:

```csharp
GlobalDI_GetService = moduleDefinition.ImportReference(UpdateMethod(globalDiType.GetMethods()
    .Single(m => m.Name == nameof(GlobalDI.GetService) && m.HasGenericParameters == true && m.Parameters.Count == 1)));
```

What are your thoughts about this?

**Comment by Keboo** [comment]
Ah right. Good catch, and yes I like the proposed change for the imports file.
