### ISSUE TITLE
Add attribute for specifying which constructor to use

### ISSUE THREAD

**Issue by Keboo** [Keboo/AutoDI#74]
Currently when [generating the factory method](https://github.com/Keboo/AutoDI/blob/master/AutoDI.Fody/ModuleWeaver.Container.cs#L120-L122) for creating objects, it simply selects the constructor with the most parameters. Though this may work in most cases, it would be nice to be able to override this behavior by decorating the expected constructor with an attribute.

- [ ] Create a new AutoDI.DiConstructorAttribute - it should specify AttributeTargets.Constructor.
- [ ] In GenerateFactoryMethod if there is a single constructor decorated with the attribute it should use that constructor. If there are multiple constructors decorated with the attribute an exception should be thrown. Otherwise, it should select the constructor with the most parameters (current logic).
- [ ] Create a new test class in [AutoDI.Fody.Tests](https://github.com/Keboo/AutoDI/tree/master/AutoDI.Fody.Tests) and add appropriate unit tests for this feature.

**Comment by rubvardanyan** [comment]
I can do it. Does anyone already started?

**Comment by Keboo** [comment]
@rubvardanyan go for it, you are the first to comment. Let me know if you have any questions/issues.
