### ISSUE TITLE
Provide compile time error when multiple constructors marked with DiConstructorAttribute

### ISSUE THREAD

**Issue by Keboo** [Keboo/AutoDI#80]
In #74 we added a new attribute to allow specifying which constructor to use. 
When there are multiple constructors marked with the `DiConstructorAttribute` it properly throws an exception which is then [caught and handled and displayed as a warning](https://github.com/Keboo/AutoDI/blob/master/AutoDI.Fody/ModuleWeaver.Container.cs#L106-L109).

Because this is a case that can easily be addressed at compile time, I think we should modify this case to log as an error rather than a warning.

I believe the following changes needs to be made:

- [x] Create a new exception type that derives from AutoDIException. This exception should live in the AutoDI.Fody project. 
- [x] When multiple constructors declare the `DiConstructorAttribute` throw the new exception instead.
- [x] Add an additional catch block [here](https://github.com/Keboo/AutoDI/blob/master/AutoDI.Fody/ModuleWeaver.Container.cs#L106-L109) to handle the exception and log an error instead.
- [x] Change the assembly generator to [throw a useful exception](https://github.com/Keboo/AutoDI/blob/master/AutoDI.AssemblyGenerator/Generator.cs#L149-L151). This new exception type should contain a collection of strings (for each of the error messages).
- [x] Fix up the unit tests. [This test](https://github.com/Keboo/AutoDI/blob/master/AutoDI.Fody.Tests/AnnotatedConstructorTest.cs#L43-L48) though should still pass after these changes should be moved into its own test class. Rather than running the assembly generator in the ClassInitialize it should be done as part of the unit test with the expectation that it throws the new exception with the error text we expect.

**Comment by rubvardanyan** [comment]
I can take this one. Just to be sure, what you mean under 
> This new exception type should contain a collection of strings (for each of the error messages).
I think we can catch that new exception type (for example `MultipleDiConstructorsFoundException`), log error and throw it.

**Comment by Keboo** [comment]
@rubvardanyan 
Right now the Generator is just [throwing a generic System.Exception](https://github.com/Keboo/AutoDI/blob/master/AutoDI.AssemblyGenerator/Generator.cs#L149-L151) and just concatenating all of the compile errors into the message. Though this is fine for the message, I would like the new exception to contain a collection (array or similar) of strings with the compile errors to give us a means of testing that a particular error occurred (string comparisons against the message of the exception always feel like a code smell).

Does that make sense?

**Comment by rubvardanyan** [comment]
Ok. I understand what you like to have. My suggestion was to break compilation process and throw exception, so the exception will be thrown from `ModuleWeaver.GenerateConfigureMethod` and there will not be need to throw that generic exception from `Generator`

**Comment by Keboo** [comment]
That would work for the unit test only. Typically the weaver will be run by MSBuild as part of the compile process. In these cases, it is better to catch the exception and call LogError so that a nice error shows up in the Visual Studio error window rather than a large ugly exception. 
Fody weavers are kind of a pain to unit test, which is why I wrote that `Generator` class. It is not a great solution, but it is the best I have at the moment.

**Comment by rubvardanyan** [comment]
Ok. I see. Thanks for explanation

**Comment by rubvardanyan** [comment]
@Keboo exception thrown from `Weaver` and not from `Generator`. Have a look [here](https://github.com/Keboo/AutoDI/blob/master/AutoDI.AssemblyGenerator/Weaver.cs#L82-L85)

**Comment by Keboo** [comment]
@rubvardanyan to clarify. [That weaver](https://github.com/Keboo/AutoDI/blob/master/AutoDI.AssemblyGenerator/Weaver.cs#L82-L85) is part of the asembly generator project (which is there only to support easier unit testing). Because this is only used as part of the unit tests, it is acceptable (and expected) to throw an exception. The weaver that I was referencing previously (the actual Fody weaver) is the [ModuleWeaver class](https://github.com/Keboo/AutoDI/blob/master/AutoDI.Fody/ModuleWeaver.cs) in the AutoDI.Fody project.

**Comment by Keboo** [comment]
@rubvardanyan just following up. Are you still working on this?

**Comment by rubvardanyan** [comment]
@Keboo yes, just don't have enough time to complete it.

**Comment by Keboo** [comment]
@rubvardanyan no problem. I may end up getting some time to work on this in the next couple of weeks. So if it is still outstanding I may just re-assign it to myself.

**Comment by rubvardanyan** [comment]
@Keboo just let me know if you are going to take this one. I am not sure that will work on it for next two weeks.

**Comment by paritoshmmmec** [comment]
@Keboo  Pull request opened. #91

**Comment by paritoshmmmec** [comment]
PR #92 Added

**Comment by Keboo** [comment]
@rubvardanyan I picked this one up and completed it.
@paritoshmmmec I started with the work that you initially PR'd, and largely just fixed up the testing issues. Thank you.

**Comment by paritoshmmmec** [comment]
@Keboo I apologise for not fixing the test thanks
