### ISSUE TITLE
Allow for debugging individual mappings

### ISSUE THREAD

**Issue by Keboo** [Keboo/AutoDI#81]
Issue #75 was a pain to track down and has made it apparent that it is not easy to debug the `<AutoDI>.AddServices()` method. What would be better is a configuration setting that would enable better exception handling in this method.

- [ ] Add a new boolean setting to the [Settings](https://github.com/Keboo/AutoDI/blob/master/AutoDI.Fody/Settings.cs) named `DebugExceptions` the default value should be false.
- [ ] When this setting is true wrap each generated method call in the `AddServices` method in a try catch block. This should build up an aggregate exception that gets thrown instead. Consider the following example, this is what is currently generated:
```C#
public static void AddServices(IServiceCollection collection)
{
    collection.AddAutoDIService<Service>((Func<IServiceProvider, object>)new Func<IServiceProvider, Service>(<AutoDI>.<Service>_generated_0), new Type[1]
    {
        typeof (IService)
    }, Lifetime.LazySingleton);
}
```
When `DebugExceptions` is true this should be generated instead.
```C#
public static void AddServices(IServiceCollection collection)
{
    var exceptions = new List<Exception>();
    try
    {
        collection.AddAutoDIService<Service>((Func<IServiceProvider, object>)new Func<IServiceProvider, Service>(<AutoDI>.<Service>_generated_0), new Type[1]
        {
            typeof (IService)
        }, Lifetime.LazySingleton);
    }
    catch (Exception ex)
    {
        exceptions.Add(new AutoDIDebugException("Error adding type 'Service' with key(s) 'IService'", ex));
    }
    if (exceptions.Count > 0)
    {
        throw new System.AggregateException("Error in <AutoDI>.AddServices() generated method", exceptions);
    }
}
```
A few notes on the above code

- Requires creating a new AutoDIDebugException
- The strings should be fixed, and generated at compile time. Don't attempt to format the string at run-time.

**Comment by tbellizzi** [comment]
Hi, I'd be interested in working on this issue. However, I would need clarification though on where the exception wrapping would take place in the code.

**Comment by Keboo** [comment]
Hi @tbellizzi 
Sure, this issue will require a bit of knowledge of CIL (common intermediate language). If you are new to Fody weavers take a look at [this blog post](https://intellitect.com/creating-fody-addin/). The `AddServices` method mentioned is generated at compile time by injecting IL commands, so inserting the the try/catch blocks will need to be done the same way.

[This method](https://github.com/Keboo/AutoDI/blob/master/AutoDI.Fody/ModuleWeaver.Container.cs#L41-L116) is the one responsible for generating the `AddServices` method. The `AddServices` method is really just a long list of `AddAutoDIService` calls. Specifically [this foreach loop](https://github.com/Keboo/AutoDI/blob/master/AutoDI.Fody/ModuleWeaver.Container.cs#L57) is the one that generates all of those calls. So for this issue, when the `DebugExceptions` setting is true we need to inject the `try/catch` IL instructions inside of this foreach loop.

I _think_ the correct CIL to generate the above will look something like this (taken from compiling the above example code; and modifying it slightly to be clearer):
```
    IL_0001: newobj       instance void class [mscorlib]System.Collections.Generic.List`1<class [mscorlib]System.Exception>::.ctor()
    IL_0006: stloc.0      // exceptions
    .try
    {   
     //Existing stuff for making the AddAutoDIService call 

      IL_0030: leave.s      IL_0049
    } // end of .try
    catch [mscorlib]System.Exception
    {
      IL_0032: stloc.1      // ex

      IL_0034: ldloc.0      // exceptions
      IL_0035: ldstr        "Error adding type 'Service' with key(s) 'IService'"
      IL_003a: ldloc.1      // ex
      IL_003b: newobj       instance void [AutoDI]AutoDI.AutoDIException::.ctor(string, class [mscorlib]System.Exception)
      IL_0040: callvirt     instance void class [mscorlib]System.Collections.Generic.List`1<class [mscorlib]System.Exception>::Add(!0/*class [mscorlib]System.Exception*/)
      IL_0045: nop          

      IL_0047: leave.s      IL_0049
    } // end of catch

    IL_0049: ldloc.0      // exceptions
    IL_004a: callvirt     instance int32 class [mscorlib]System.Collections.Generic.List`1<class [mscorlib]System.Exception>::get_Count()
    IL_004f: ldc.i4.0     
    IL_0050: cgt          
    IL_0054: brfalse.s    IL_0063 

    IL_0057: ldstr        "Error in <AutoDI>.AddServices() generated method"
    IL_005c: ldloc.0      // exceptions
    IL_005d: newobj       instance void [mscorlib]System.AggregateException::.ctor(string, class [mscorlib]System.Collections.Generic.IEnumerable`1<class [mscorlib]System.Exception>)
    IL_0062: throw        
```

Obviously some of the symbols in the above CIL will need to be dynamic when they are being output such as the type names.

**Comment by tbellizzi** [comment]
Hi @Keboo, thanks for the in-depth breakdown and well written post, it helped clear up a lot. This is my first time working with Fody weavers but am interested in learning. I will see how far I get and update you.

**Comment by Keboo** [comment]
@tbellizzi great. If you have questions or issues just let me know.
