### ISSUE TITLE
Separate AssemblyGenerator into its own nuget package

### ISSUE THREAD

**Issue by Keboo** [Keboo/AutoDI#95]
Since Fody weavers are expected to run as part of the build process, it can be difficult to unit test all of the functionality, especially if the weaver is expected to log errors in some cases.

The assembly generator allows for taking some small bit of code (currently declared inline and wrapped in comments) and compiling it into an assembly that the weaver is then run against. It attempts to simulate the build process, and allows for stepping into the weaver to debug it (something I have gotten a lot of use out of). 

Some of the unit testing does get a little weird around types. The types the unit test is compiled against are _**different**_ from the types that the test is run against. At compile time the unit test is compiled against the types declared inline (this are apart of the unit test assembly). When the test is run, this code is lifted out of the unit test file, and used to create types in a new assembly. These new types are what the tests are run against. 
This feels weird and sort of pushed DLR usage. At some point should consider alternatives.

For MVP I believe the following is needed:

- [ ] remove the [project reference to AutoDI](https://github.com/Keboo/AutoDI/blob/master/AutoDI.AssemblyGenerator/AutoDI.AssemblyGenerator.csproj#L16).
- [ ] move any AutoDI specific bits into the unit test projects. The  `AssemblyMixins.Resolve<T>` is the obvious method that needs to be moved.
- [ ] generate nuget package for the assembly generator
- [ ] reference the nuget package in the AutoDI tests.
- [ ] consider separating it off into its own repository
- [ ] consider renaming it to something more generic. FodyWeaver.Testing.AssemblyGenerator?

**Comment by InKahootz** [comment]
Did you still want help with this or has the scope changed too much? The project structure has changed a little and Fody was removed near October 2018. Just been looking to help around for Hacktoberfest.

**Comment by Keboo** [comment]
Hi @InKahootz yea this issue has gotten a little stale, but I would still love help with it.
Rather than making it into its own NuGet package I think a simpler first step would simply be to refactory [AutoDI.AssemblyGenerator](https://github.com/Keboo/AutoDI/tree/master/AutoDI.AssemblyGenerator) to remove the [hard reference to AutoDI](https://github.com/Keboo/AutoDI/blob/master/AutoDI.AssemblyGenerator/AutoDI.AssemblyGenerator.csproj#L24). 
If we can get it that far, then it will make it easier to get it to its own package in the future.
